# Development

name = "auth-dev"
account_id = "fffa4b4363a7e5250af8357087263b3a"
main = "./dist/worker.js"

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2022-04-26"

[vars]
ENV = "dev"
DEBUG = "false"

[build]
command = "scripts/cli.js build"
watch_dir = "src"

