# Development

name = "w3access-test"
account_id = "fffa4b4363a7e5250af8357087263b3a"
main = "./dist/worker.js"

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2022-06-26"
compatibility_flags = ["url_standard"]
no_bundle = true

[[kv_namespaces]]
binding = "ACCOUNTS"
id = "e9fad7e04b254bf49206e08e50074387"

[[kv_namespaces]]
binding = "VALIDATIONS"
id = "62e57652625c44a3b1fef2f840ffc882"

[vars]
ENV = "dev"
DEBUG = "true"

[build]
command = "scripts/cli.js build"
watch_dir = "src"


# Dev
[env.dev]
name = "w3access-dev"
workers_dev = true

[env.dev.vars]
ENV = "dev"
DEBUG = "false"

[env.dev.build]
command = "scripts/cli.js build --env dev"
watch_dir = "src"

[[env.dev.kv_namespaces]]
binding = "ACCOUNTS"
id = "5697e95e1aaa436788e6d697fd3350be"

[[env.dev.kv_namespaces]]
binding = "VALIDATIONS"
id = "ea17f472b37a43d29c1faf7af9512e03"

# Staging
[env.staging]
name = "w3access-staging"
routes = [{ pattern = "access-api-staging.web3.storage", custom_domain = true }]

[env.staging.vars]
ENV = "staging"
DEBUG = "false"

[env.staging.build]
command = "scripts/cli.js build --env staging"
watch_dir = "src"

[[env.staging.kv_namespaces]]
binding = "ACCOUNTS"
id = "b0e5ca990dda4e3784a1741dfa28a52e"

[[env.staging.kv_namespaces]]
binding = "VALIDATIONS"
id = "b13f07c88fe848db9ccf651a0fea3fb6"


# Production
[env.production]
name = "w3access"
routes = [{ pattern = "access-api.web3.storage", custom_domain = true }]

[env.production.vars]
ENV = "production"
DEBUG = "false"

[env.production.build]
command = "scripts/cli.js build --env production"
watch_dir = "src"

[[env.production.kv_namespaces]]
binding = "ACCOUNTS"
id = "5437954e8cfd4f7d98557132b0a2e93f"

[[env.production.kv_namespaces]]
binding = "VALIDATIONS"
id = "fb7cf10c725f45948321e88b8cb168ad"
