# Development
name = "w3access-test"
account_id = "fffa4b4363a7e5250af8357087263b3a"
main = "./dist/worker.js"

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2022-09-28"
compatibility_flags = ["url_standard"]

# We need to let wrangler bundle while D1 is in Beta
no_bundle = false

[[kv_namespaces]]
binding = "SPACES"
id = "e9fad7e04b254bf49206e08e50074387"
preview_id = "e9fad7e04b254bf49206e08e50074387"

[[kv_namespaces]]
binding = "VALIDATIONS"
id = "62e57652625c44a3b1fef2f840ffc882"
preview_id = "62e57652625c44a3b1fef2f840ffc882"

[[d1_databases]]
binding = "__D1_BETA__"
database_name = "spaces-dev"
database_id = "7c676e0c-b9e7-4711-97c8-7b1c8eb229ae"

[vars]
ENV = "dev"
DEBUG = "true"


[build]
command = "scripts/cli.js build"
watch_dir = "src"

[miniflare]
d1_persist = ".wrangler/miniflare"


# Dev
[env.dev]
name = "w3access-dev"
workers_dev = true
vars = { ENV = "dev", DEBUG = "false", DID = "did:web:dev.web3.storage" }
build = { command = "scripts/cli.js build --env dev", watch_dir = "src" }
kv_namespaces = [
    { binding = "SPACES", id = "5697e95e1aaa436788e6d697fd3350be" },
    { binding = "VALIDATIONS", id = "ea17f472b37a43d29c1faf7af9512e03" },
]
d1_databases = [
    { binding = "__D1_BETA__", database_name = "access-dev", database_id = "4145a261-e54c-411d-a001-050fc30e4678" },
]
unsafe = { bindings = [
    { type = "analytics_engine", dataset = "W3ACCESS_METRICS", name = "W3ACCESS_METRICS" },
] }


# Staging
[env.staging]
name = "w3access-staging"
workers_dev = true
vars = { ENV = "staging", DEBUG = "false", DID = "did:web:staging.web3.storage" }
build = { command = "scripts/cli.js build --env staging", watch_dir = "src" }
kv_namespaces = [
    { binding = "SPACES", id = "b0e5ca990dda4e3784a1741dfa28a52e" },
    { binding = "VALIDATIONS", id = "b13f07c88fe848db9ccf651a0fea3fb6" },
]
d1_databases = [
    { binding = "__D1_BETA__", database_name = "access-staging", database_id = "16f0660e-2a8e-4e13-9f05-0a2a594d91ed" },
]
unsafe = { bindings = [
    { type = "analytics_engine", dataset = "W3ACCESS_METRICS", name = "W3ACCESS_METRICS" },
] }


# Production
[env.production]
name = "w3access"
routes = [{ pattern = "access.web3.storage", custom_domain = true }]
vars = { ENV = "production", DEBUG = "false", DID = "did:web:web3.storage" }
build = { command = "scripts/cli.js build --env production", watch_dir = "src" }
kv_namespaces = [
    { binding = "SPACES", id = "5437954e8cfd4f7d98557132b0a2e93f" },
    { binding = "VALIDATIONS", id = "fb7cf10c725f45948321e88b8cb168ad" },
]
d1_databases = [
    { binding = "__D1_BETA__", database_name = "access", database_id = "d9e83dff-d023-4206-9cf9-d11135bbe0b7" },
]
unsafe = { bindings = [
    { type = "analytics_engine", dataset = "W3ACCESS_METRICS", name = "W3ACCESS_METRICS" },
] }
