name: blob-index
on:
  push:
    branches:
      - main
    paths:
      - 'packages/blob-index/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/blob-index.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/blob-index/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/blob-index.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/blob-index
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: pnpm/action-setup@v4
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm --filter '@web3-storage/blob-index...' install
      - run: pnpm --filter '@web3-storage/blob-index' lint
      - run: pnpm --filter '@web3-storage/blob-index' test
