name: Release
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          default-branch: main
          release-type: node
  publish-access:
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/access-client')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/access build
      - run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-upload-client:
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/upload-client')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/upload-client build
      - run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  pages:
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/wallet')
    runs-on: ubuntu-latest
    steps:
      - run: echo 'pages'
  worker:
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/access-api')
    uses: './.github/workflows/reuse-deploy-api.yml'
    with:
      environment: production
      environment_url: https://access.web3.storage
    secrets: inherit
