name: Upload Client
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
    paths:
      - 'packages/upload-client/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/client.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/upload-client/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/client.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter @web3-storage/upload-client run lint
      - run: pnpm -r --filter @web3-storage/upload-client run test
      - run: pnpm -r --filter @web3-storage/upload-client exec depcheck
