name: w3up-client
on:
  push:
    branches:
      - main
    paths:
      - 'packages/w3up-client/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/w3up-client.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/w3up-client/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/w3up-client.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18
          - 20
    defaults:
      run:
        working-directory: ./packages/w3up-client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 8
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm --filter '@web3-storage/w3up-client...' install
      - run: pnpm --filter '@web3-storage/w3up-client' attw
      - uses: ./packages/w3up-client/.github/actions/test
        with:
          w3up-client-dir: ./packages/w3up-client/
